<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <title>Exitus</title>
    <!-- Bootstrap Core CSS -->
    <link href="material/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- chartist CSS -->
    <link href="material/assets/plugins/chartist-js/dist/chartist.min.css" rel="stylesheet">
    <link href="material/assets/plugins/chartist-js/dist/chartist-init.css" rel="stylesheet">
    <link href="material/assets/plugins/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.css" rel="stylesheet">
    <!--This page css - Morris CSS -->
    <link href="material/assets/plugins/c3-master/c3.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="material/css/style.css" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="material/css/colors/megna-dark.css" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body class="fix-header fix-sidebar card-no-border logo-center">
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <header class="topbar">
            <nav class="navbar top-navbar navbar-expand-md navbar-light">
                <div class="navbar-collapse">
                    <hi class=" card-title text-white">Exitus CRUD</hi>
                </div>
            </nav>
        </header>
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container">
                <!-- ============================================================== -->
                <!-- Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <div class="row page-titles">
                    <div class="col-md-10 col-10 align-self-center">
                        <h3 class="text-themecolor">Lista usuarios</h3>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0)">Usuarios</a></li>
                        </ol>
                    </div>
                    <div class="col-md-2 col-2 align-self-center">
                        <a class="btn btn-success" href="usuario/nuevo"><i class="mdi mdi-account-plus"></i>  Nuevo Usuario</a>
                    </div>
                </div>
                <div class="row">
                    <!-- Column -->
                    <div class="col-lg-12 col-xlg-12 col-md-12">
                        <div class="card">
                            <div class="card-body">
                              <div class="d-flex flex-wrap">
                                  <div class="table-responsive">
                                            <table class="table full-color-table full-inverse-table hover-table">
                                                <thead>
                                                    <tr>
                                                        <th>#</th>
                                                        <th>Nombre</th>
                                                        <th>Apellido paterno</th>
                                                        <th>Detalles</th>
                                                        <th>Editar</th>
                                                        <th>Eliminar</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                  <?php
                                                    $contador=1;
                                                    foreach ($datos as $dato) {
                                                  ?>
                                                  <tr>
                                                    <td><?php echo $contador++;?></td>
                                                    <td><?php echo $dato['nombre'];?></td>
                                                    <td><?php echo $dato['apellido_paterno'];?></td>
                                                    <td><a href=""><i class="mdi mdi-account-card-details"></i></a></td>
                                                    <td class="align-text-center"><a href="usuario/editar/<?php echo $dato['id'];?>"><i class="mdi mdi-account-edit" width="30px"></i></a></td>
                                                    <td class="align-text-center"><a href="<?php echo $dato['id'];?>"><i class="mdi mdi-delete-circle"></i></a></td>
                                                  </tr>
                                                <?php
                                                  }
                                                ?>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>


                                </div>

                                <div class="row text-center">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- ============================================================== -->
                <!-- End Right sidebar -->
                <!-- ============================================================== -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- footer -->
            <!-- ============================================================== -->
            <footer class="footer"> © 2017 Exitus Examen Tecnico By Harold Romero </footer>
            <!-- ============================================================== -->
            <!-- End footer -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="material/assets/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="material/assets/plugins/bootstrap/js/popper.min.js"></script>
    <script src="material/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="material/js/jquery.slimscroll.js"></script>
    <!--Wave Effects -->
    <script src="material/js/waves.js"></script>
    <!--Menu sidebar -->
    <script src="material/js/sidebarmenu.js"></script>
    <!--stickey kit -->
    <script src="material/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
    <script src="magterial/assets/plugins/sparkline/jquery.sparkline.min.js"></script>
    <script src="material/assets/plugins/sparkline/jquery.sparkline.min.js"></script>
    <!--Custom JavaScript -->
    <script src="material/js/custom.min.js"></script>
    <!-- ============================================================== -->
    <!-- This page plugins -->
    <!-- ============================================================== -->
    <!-- chartist chart -->
    <script src="material/assets/plugins/chartist-js/dist/chartist.min.js"></script>
    <script src="material/assets/plugins/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.min.js"></script>
    <!--c3 JavaScript -->
    <script src="material/assets/plugins/d3/d3.min.js"></script>
    <script src="material/assets/plugins/c3-master/c3.min.js"></script>
    <!-- Chart JS -->
    <script src="material/js/dashboard1.js"></script>
    <!-- ============================================================== -->
    <!-- Style switcher -->
    <!-- ============================================================== -->
    <script src="material/assets/plugins/styleswitcher/jQuery.style.switcher.js"></script>
</body>

</html>
