<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Exitus CRUD</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    </head>
    <body>
      <div style="background: #FA5858;"class="text-white "><h1>Exitus</h1></div>
      <div class="container">
        <div class="text-center">
          <h2 class="sub-header">Usuarios Registrados</h2>
        </div>
        <div class="row">
          <a class="btn btn-success" href="usuario/nuevo"><i class="far fa-id-card"></i>  Nuevo Usuario</a>
        </div><br>
        <div class="row">
          <table class="table">
            <tr>
              <td>#</td>
              <td>Nombre</td>
              <td>Apellido paterno</td>
              <td>Apellido Materno</td>
              <td>Fecha de nacimiento</td>
              <td>Editar</td>
              <td>Eliminar</td>
            </tr>
            <?php
              $contador=1;
              foreach ($datos as $dato) {
            ?>
            <tr>
              <td><?php echo $contador++;?></td>
              <td><?php echo $dato['nombre'];?></td>
              <td><?php echo $dato['apellido_paterno'];?></td>
              <td><?php echo $dato['apellido_materno'];?></td>
              <td><?php echo $dato['fecha_nacimiento'];?></td>
              <td><center><a href="usuario/editar/<?php echo $dato['id'];?>"><i class="far fa-edit"></i></a></center></td>
              <td><center><a href="<?php echo $dato['id'];?>"><i class="fas fa-trash-alt"></i></a></center></td>
            </tr>
          <?php
            }
          ?>
          </table>

        </div>
      </div>






    </body>
</html>
